### ISSUE TITLE
Vary fixation symbol to better delineate trial stages

### ISSUE THREAD

**Issue by tsalo** [adamkimbler/math_task#24]
This will help participants who zone out and are confused on a baseline trial. From @62442katieb.

**Comment by tsalo** [comment]
@62442katieb any thoughts on what specifically you'd like to see here?

**Comment by 62442katieb** [comment]
As I mentioned when we ran it at the mock on Thursday, a triangle would do fine. I think the specifics are trivial, as long as it's discernably different from the circle fixation.

**Comment by tsalo** [comment]
I tried to use a unicode triangle but for some reason it kept getting cut off, so in #30 I changed the color of the fixation dot.
- Pre-task: white
- ISI1 (between equation and comparison): red
- ISI2 (between comparison and feedback): white
- ITI (between feedback and next trial's equation): white

@62442katieb WDYT?
