### ISSUE TITLE
No zero stimulus

### ISSUE THREAD

**Issue by tsalo** [adamkimbler/math_task#4]
While testing participant 002 session 1, I got the following error:

```
OSError: Couldn't find image /Users/tsalo/Documents/nbc/math_task/numerals/00a.png; check path? (tried: /Users/tsalo/Documents/nbc/math_task/numerals/00a.png)
```

One of the trials has the comparison 19-0 but there is no image for zero.

**Comment by akimbler** [comment]
Fixed with recent commit
