### ISSUE TITLE
Runs are too short

### ISSUE THREAD

**Issue by tsalo** [adamkimbler/math_task#5]
Runs (which require a space or 5 to continue from) are only about 1.5 minutes long. Is there some variable that needs to be changed to run 7.5 minute runs?

Also it looks like there are three runs but there should only be too, right? Tagging @62442katieb to be sure.

**Comment by 62442katieb** [comment]
Confirmed, there should be 2 runs of 7.5 minutes each

**Comment by akimbler** [comment]
@tsalo @62442katieb The main cause of this should be fixed in #7. Before I merge, we should probably talk about adding the duration of ITIs to the config file and how we want to go about doing that.

**Comment by tsalo** [comment]
It might be a good idea to do that. Maybe instead of presetting all of the ITIs in a specific order, like we do with the localizer task, we could set a list of ITIs that are then just drawn randomly across all runs. One set of ITIs for all the runs and sessions. Thoughts?

**Comment by tsalo** [comment]
Now it's wayyyyyyyy too long. Each run seems to be at least 22 minutes long and there are at least three runs (I quit after the third run started).
