### ISSUE TITLE
Improve trial timing

### ISSUE THREAD

**Issue by tsalo** [adamkimbler/math_task#9]
We touched on this in #5, but I want to put it in its own issue.
To do:
1. Jitter ITIs
2. Jitter ISIs
3. Jitter stimulus durations
4. Add lead-out screen for ~2 seconds after scan ends

**Comment by tsalo** [comment]
I started working on this in [this notebook](https://github.com/tsalo/math_task/blob/master/determine_timing.ipynb).

We will generate a set of times that work within our constraints and then just randomly shuffle them on a run-by-run basis.

The questions remaining are 1) what ranges should we use for the different stages, 2) should we use uniform distributions or something else, and 3) how many trials do we want to fit into our 7.5 minute runs.

**Comment by tsalo** [comment]
Per meeting with @mattfeld, we want to use a ~exponential~ right-skewed Gumbel distribution cropped to 2-8s for ISIs and ITIs, set feedback at 500ms with no variability, and shorten the equation and comparison slide durations to as short as we can get them.

**Comment by mattfeld** [comment]
@tsalo also note:  your ISI should be drawn from a distribution with a mean of ~4s and it is worth considering having approximately 1/3 of your trials be true null trials that have similar operations to the equations, comparisons, and feedback conditions minus the construct you are interested in. Perhaps logic problems OR that is where you could do those numeracy judgement types of trials that have different colored dots (see this paper: https://www.nature.com/articles/nature07246.pdf)
